# -*- encoding: utf-8 -*-
{
    'name': 'Odoo Mocks',
    'version': '0.1',
    'category': 'Library',
    'license': 'AGPL-3',
    'summary': '',
    'description': """ Example of using Mocks in Odoo Tests """,
    'author': 'Colin Wren',
    'website': 'http://colinwren.is/mocking-out-registries-in-odoo-tests.html',
    'depends': ['mail'],
    'data': [],
    'demo': ['data/demo.xml'],
    'css': [],
    'js': [],
    'qweb': [],
    'images': [],
    'application': True,
    'installable': True,
    'active': False,
}